### ISSUE TITLE
pgdeploy runs into errors while switchover commands triggers it

### ISSUE THREAD

**Issue by mfuhrmann** [Proemion/repmgr-agent#14]
Today while we did https://github.com/Proemion/it-internal/issues/593 we've noticed that pgdeploy is not working properly.

Those errors appeared within the normal switchover commands:
```
DETAIL: promoting server "frapspdb_n0" (ID: 1) using pg_promote()
NOTICE: waiting up to 60 seconds (parameter "promote_check_timeout") for promotion to complete
NOTICE: STANDBY PROMOTE successful
DETAIL: server "frapspdb_n0" (ID: 1) was successfully promoted to primary
INFO: executing notification command for event "standby_promote"
DETAIL: command is:
  /usr/share/repmgr-agent/pgdeploy -c proemion -p port=5432 -P
Exception in thread 10.10.2.64:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

Exception in thread 172.21.70.153:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

Exception in thread 172.21.70.152:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

INFO: local node 2 can attach to rejoin target node 1
DETAIL: local node's recovery point: 69DE/61000028; rejoin target node's fork point: 69DE/610000A0
NOTICE: setting node 2's upstream to node 1
WARNING: unable to ping "host=192.168.145.22 user=postgres port=5432 application_name=frapspdb_n1"
DETAIL: PQping() returned "PQPING_NO_RESPONSE"
NOTICE: starting server using "sudo systemctl start postgresql@12-main.service"
NOTICE: replication slot "repmgr_slot_1" deleted on node 2
WARNING: 1 inactive replication slots detected
DETAIL: inactive replication slots:
  - repmgr_slot_3 (physical)
HINT: these replication slots may need to be removed manually
NOTICE: NODE REJOIN successful
DETAIL: node 2 is now attached to node 1
INFO: executing notification command for event "standby_switchover"
DETAIL: command is:
  /usr/share/repmgr-agent/pgdeploy -c proemion -p port=5432 -P
Exception in thread 10.10.2.64:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

Exception in thread 172.21.70.152:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

Exception in thread 172.21.70.153:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/repmgr-agent/pgdeploy", line 110, in safe_deploy
    return self.deploy(remote_host)
  File "/usr/share/repmgr-agent/pgdeploy", line 131, in deploy
    with shell.open(cluster_config, "wb") as pgbouncer:
  File "/usr/lib/python3/dist-packages/spur/ssh.py", line 234, in open
    sftp_file = SftpFile(sftp, sftp.open(name, mode), mode)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

**Comment by jamie-staib** [comment]
@mfuhrmann This is probably related to https://github.com/Proemion/repmgr-agent/issues/12 where we migrated to python3. Will need to figure out if we missed some needed changes. 

For claas pro PG I don't remember any errors while we performed the switchover, so this may only be affecting the ubuntu 18.08 versions.

**Comment by jamie-staib** [comment]
On PSP pro PG we have 4 services defined. 

```
postgres=# SELECT *
postgres-# FROM repmgr.app_servers;
 node_id | node_name  |    ip_addr    | username |    application_name    | enabled | auth_trust 
---------+------------+---------------+----------+------------------------+---------+------------
      23 | frapevm012 | 172.21.70.151 | postgres | PSP-FRA-PGB            | t       | f
      22 | frapevm014 | 172.21.70.153 | postgres | PSP-FRA-CLI            | t       | f
      34 | pevm061    | 10.10.2.64    | postgres | batch-device-processor | t       | f
      36 | frapevm013 | 172.21.70.152 | postgres | PSP-FRA-PRS            | t       | f
```

Only three of them failed. Checking pgbouncer, it looks like pgdeploy correctly applied the changes when we performed the switchover.

```
[12:13]root@frapevm012:/etc/pgbouncer# grep SIGHU /var/log/postgresql/pgbouncer.log
2021-07-22 07:20:48.247 UTC [17359] LOG got SIGHUP, re-reading config
2021-07-22 07:39:47.284 UTC [17359] LOG got SIGHUP, re-reading config
```

The other three nodes do not have pgbouncer installed. It was removed when we cleaned up all the services that did no longer use pgbouncer.

We do not have any sanity checks in pgdeploy so it ends up complaining with a `FileNotFoundError: [Errno 2] No such file
` as it can not find the two files it tries to open and edit on the clients.

> cluster_config = "/etc/pgbouncer/databases/%s.ini" % self.cluster_name
> with shell.open(cluster_config, "wb") as pgbouncer:
> 
> with shell.open("/etc/pgbouncer/userlist.txt", "wb") as userlist:

So I believe the fix is cleaning up the incorrectly defined applications from `repmgr.app_servers`

**Comment by jamie-staib** [comment]
I propose we remove the incorrect entries from `repmgr.app_servers`.

```
DELETE FROM repmgr.app_servers
WHERE node_id=22;
DELETE FROM repmgr.app_servers
WHERE node_id=34;
DELETE FROM repmgr.app_servers
WHERE node_id=36;
```

@mfuhrmann @bs1008 wdyt?

**Comment by bs1008** [comment]
@jamie I double-checked the suggested DELETE statements.
Yes, please run these 3 suggested `delete` statements, and then we should be fine.

**Comment by jamie-staib** [comment]
Removed the incorrect entries from `repmgr.app_servers`.
