### ISSUE TITLE
pgdeploy doesn't work in a single PSQL-instance environment

### ISSUE THREAD

**Issue by mfuhrmann** [Proemion/repmgr-agent#4]
In past we had run 3 PSQL instances on one server. That's why we needed a differentation of repmgr table. They were called repmgr.claas, repmgr.linde, repmgr.proemion,

In a single PSQL instance environment the DB is called **main** and the repmgr table is only called **repmgr**.
See output below:

```
[10:02]postgres@dev-psql-linde-n1:/root# /usr/share/repmgr-agent/pgdeploy -c main -p port=5432 -P
Traceback (most recent call last):
  File "/usr/share/repmgr-agent/pgdeploy", line 174, in <module>
    sys.exit(main())
  File "/usr/share/repmgr-agent/pgdeploy", line 170, in main
    updater = PgBouncerUpdater(options.cluster, options.pgconnstring, options.timeout, options.public_net)
  File "/usr/share/repmgr-agent/pgdeploy", line 48, in __init__
    """ORDER BY id""" % self.cluster_name
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: relation "repmgr_main.repl_nodes" does not exist
LINE 1: SELECT id, name, type, conninfo FROM repmgr_main.repl_nodes ...
```

**Comment by mfuhrmann** [comment]
Fixed version is available here: https://github.com/mfuhrmann/repmgr-agent

**Comment by Svedrin** [comment]
@mfuhrmann PR? :P

**Comment by mfuhrmann** [comment]
https://github.com/Proemion/repmgr-agent/pull/5

**Comment by Svedrin** [comment]
@mfuhrmann if you write "fixes #4" into the PR's description, the PR will appear here and auto-close this issue when merged :)
